### ISSUE TITLE
scriptworker 0.1.0

### ISSUE THREAD

**Issue by escapewindow** [escapewindow/scriptworker#1]
@jonasfj @djmitche @gregarndt @petemoore @imbstack any thoughts/questions on this before 0.1.0?

**Comment by petemoore** [comment]
Looks like a great start, nice work Aki!

Would be good to enable the travis build (I couldn't see it under https://travis-ci.org/escapewindow) and also maybe add a travis badge. Also it would be good to enable the coverage reports (https://coveralls.io/github/escapewindow).

The `tox` setup isn't working for me...

```
(scriptworker) petermoore@Peter-Moores-MacBook-Pro:~/git/scriptworker master $ python --version
Python 3.5.1
(scriptworker) petermoore@Peter-Moores-MacBook-Pro:~/git/scriptworker master $ tox
ERROR: unknown environment 'py35'
```

I also noticed the `.travis.yml` file runs `travis_retry pip install tox==1.8` but since it is using python 3.5, and pip is included with python since python 3.4, it might be better to use `python -m pip install tox==1.8` to use the built in pip.

When I remove references to `py35` in the tox setup, I get just one test failure:

```
========================================================================== FAILURES ==========================================================================
___________________________________________________________ TestUtils.test_datestring_to_timestamp ___________________________________________________________

self = <tests.test_utils.TestUtils object at 0x10d5f4ac8>, datestring = '2016-04-16T03:46:24.958Z'

    def test_datestring_to_timestamp(self, datestring):
>       assert utils.datestring_to_timestamp(datestring) == 1460803584.0
E       assert 1460771184.0 == 1460803584.0
E        +  where 1460771184.0 = <function datestring_to_timestamp at 0x10d4c1268>('2016-04-16T03:46:24.958Z')
E        +    where <function datestring_to_timestamp at 0x10d4c1268> = utils.datestring_to_timestamp

tests/test_utils.py:87: AssertionError
============================================================ 1 failed, 61 passed in 40.22 seconds ============================================================
ERROR: InvocationError: '/Users/petermoore/git/scriptworker/.tox/python/bin/py.test --cov=scriptworker --cov-report term-missing'
python runtests: commands[2] | coverage html
python runtests: commands[3] | flake8
__________________________________________________________________________ summary ___________________________________________________________________________
ERROR:   python: commands failed
```

It is great that the test run tells you how to set up test config. ++ for that. :)

The only other thing I noticed was that the test told me how to set up test config with an access token and client id, but didn't mention how to specify a certificate (in the case of using temp credentials). Is it possible also to run tests with temp credentials?

Thanks Aki!

**Comment by escapewindow** [comment]
> Looks like a great start, nice work Aki!
Thanks!

> Would be good to enable the travis build (I couldn't see it under https://travis-ci.org/escapewindow) and also maybe add a travis badge. Also it would be good to enable the coverage reports (https://coveralls.io/github/escapewindow).

Done.

> The tox setup isn't working for me...

I fixed the `README.md` and `.travis.yml` to be more accurate, and it's working on travis now.

> When I remove references to py35 in the tox setup, I get just one test failure:

I had a bug in the datetime code, and the fact that you're in a different timezone helped uncover it, thank you :)  I started using `arrow` which is a lot less footgun-y.

`10:39 <•aki> arrow.get(isoformat).timestamp is so much nicer than datestring = datestring.split('.')[0]; calendar.timegm(datetime.datetime.strptime(datestring, "%Y-%m-%dT%H:%M:%S").utctimetuple())`

> The only other thing I noticed was that the test told me how to set up test config with an access token and client id, but didn't mention how to specify a certificate (in the case of using temp credentials). Is it possible also to run tests with temp credentials?

It wasn't possible before.  Just now added temp cred support for integration tests, though I'm currently using real creds with limited scopes.  Do you see that as a common use case?

**Comment by escapewindow** [comment]
(I have 100% test coverage with integration tests, 97.28% without)

**Comment by petemoore** [comment]
Great Aki, thanks for the updates!

> It wasn't possible before. Just now added temp cred support for integration tests, though I'm currently using real creds with limited scopes. Do you see that as a common use case?

We typically run workers with temp creds (provided by the provisioner), just to limit the damage that could be done if somebody was able to get hold of them. For example to avoid that they can perform a delayed attack (as the credentials should expire) and also to isolate them to only having credentials valid for that particular `workerId` without needing to create unique permanent creds for each worker (e.g. so they can't resolve tasks that another worker has claimed).

**Comment by escapewindow** [comment]
To sum up temp creds:

In #taskcluster, we found we were talking about different things:

```irc
09:13 <aki> for integration, assume:project:taskcluster:worker-test-scopes is limited to dummy-worker-*
09:14 <•pmoore> aki: sorry, this has been a misunderstanding on my part - i was talking about production credentials - for the test worker i think that is fine
09:14 <•pmoore> sorry, i should have read the scope name better!
09:14 <aki> ok, i thought you were talking about tests. i wasn't intending to touch prod at all
```

The benefit of temporary credentials on **prod** is that a compromised worker can only give temporary credentials, which have both limited scopes and limited lifespan.  The provisioner creates the temporary credentials and gives them to the worker.

For scriptworker, we don't have a provisioner.  The workers are locked down, the tasks are signed, and for signing we will have a whitelist of machines that can access the signing servers.  We might be able to get away with just the former:

```irc
09:22 <•garndt> aki: so for the creds used in prod, every machine that is spawned gets a set of temp creds from our provisioner that has these scopes: https://tools.taskcluster.net/auth/roles/#worker-type:aws-provisioner-v1%252f*
09:22 <•garndt> aki: which gives the worker jsut enough privileges to do worker things
09:22 <•garndt> aki: like polling for tsaks, claiming and resolving them
09:23 <aki> garndt: ok. we won't have a provisioner. should we generate long-lived temp creds manually or use perm creds?
09:23 <•garndt> aki: if you are not having instances provisioned by our provisioner (like having a box in releng running the signing worker) then you do not get these temp creds, you'll probably want to have a set of perma creds used by that worker and use that role as a guideline of perms needed
09:23 <aki> ok :)
09:24 <•garndt> aki: from there, once a task is claimed, the claim response from the queue includes a set of temp creds based on the scopes of that task, we then use those scopes for any taskcluster related activity related to the task (such as creating an artifact)
```

However, if we also want to put time limits on the worker credentials, we could create temp creds and push them out to the workers via puppet.  According to http://docs.taskcluster.net/manual/apis/temporary-credentials , temp creds are limited to 31 day lifetimes, so we would need to do this temp cred creation & push every few weeks.

I think it would be nice to have the option to use temporary credentials.  The sec team could mandate their use before we enable these workers for production.  I'll keep temp creds on my todo list, but I may decide to not block 0.1.0 on them.

**Comment by djmitche** [comment]
I don't see a big benefit to using temporary credentials in this case.  If the worker hosts are compromised, you're already in worse trouble than being able to claim tasks.  A month-long temporary credential leaves plenty of time for use by Mallory, too.  And the risk of outages due to renewal failures is pretty high -- that sounds complicated, especially if done via puppet (does someone need to land a puppet patch every 3 weeks?)

Rather, I'd recommend making a disctint permacred for each host.  That will give us a more granular view of which host is doing what, and limit the damage from an accidental (e.g., pastebin) disclosure.

**Comment by escapewindow** [comment]
Thanks Dustin!

I thought about abandoning the https://github.com/escapewindow/scriptworker/tree/temp_creds branch, but then I thought it might be good to be able to reload permacreds on each running instance.  That allows us the capability of easily rotating permacreds, without the hard 31 day time limit of temp creds.

**Comment by petemoore** [comment]
> I don't see a big benefit to using temporary credentials in this case. If the worker hosts are compromised, you're already in worse trouble than being able to claim tasks.

If a worker host is compromised, you are in as much trouble as the worker has capacity to perform. The more freedom it has, the more freedom an attacker has. Therefore we should restrict the permissions we give the credentials in order to reduce the attack surface of an attacker once they have gained the credentials. This is best done using temporary credentials.

> A month-long temporary credential leaves plenty of time for use by Mallory, too.

They temp credentials could be valid e.g. for a number of hours, there is no reason they would need to be valid for a month.

> And the risk of outages due to renewal failures is pretty high -- that sounds complicated, especially if done via puppet (does someone need to land a puppet patch every 3 weeks?)

I would propose not to use puppet, but to use a provisioner. Or will these workers not be running in a cloud? I don't see a risk of renewal failures over other kinds of failures. We rely on many micro services in order to operate, and this would just be one of those. Whatever spawns the worker could also provide its credentials, and that worker could be given a limited lifetime.

> Rather, I'd recommend making a distinct permacred for each host. That will give us a more granular view of which host is doing what, and limit the damage from an accidental (e.g., pastebin) disclosure.

Permanent credentials would not give a more granular view than temporary credentials, since temp creds can include the host name in their name. The temp credentials would give a more granular view. Also, a pastebin disclosure of a temporary credential is usually less serious than a pastebin disclosure of a permanent credential, since the scopes it has can be fine tuned to be just those that are absolutely needed.

Managing a discrete set of permanent credentials per host would bloat the central registry of clients registered with the auth service.

In TaskCluster operations, all of our workers now use temporary credentials. We used to use permanent credentials too, but we moved away from this, for the heightened security. I believe the arguments for RelEng to use temp creds would be the same as they were for the TaskCluster team. 

I would propose we aim to keep the number of permanent clients we use limited to e.g. long running services, and use temporary clients for ad-hoc activities such as running workers, and executing tasks on workers. TaskCluster encourages this lightweight usage which keeps the client registry lean, and increases security by exposing permanent credentials in fewer places.

Since the python client library already supports using temporary credentials, I think it would make sense for scriptworker to support them too (without too much work), and then the details about how the credentials get rolled out to the workers can be worked out later. If it is decided they should use permanent credentials, having support for temporary credentials would not block that.

**Comment by djmitche** [comment]
My understanding is that these will not be cloud-based, as they need to be co-located with the signing servers themselves and granted limited access via network ACLs.

If an attacker compromises a signing worker, then the TC credentials on that worker are no longer of use to the attacker: they have what they came for, open access to the signing servers.  The credentials in question aren't able to do much but claim tasks for this particular worker.

Regarding disclosure, keep in mind that we cannot revoke temporary credentials, whereas we can revoke permanent credentials.  (Well, we can, but we must revoke *all* temporary credentials which will cause all running worker instances and tasks to fail and log everyone out of tools)

I think of these workers as more like a microservice than like a TC worker instance.  It just happens this particular microservice uses the queue as its API, rather than exposing it via HTTP.  And all of our microservices use permanent credentials.

**Comment by escapewindow** [comment]
In a way, you're both right.

> If an attacker compromises a signing worker, then the TC credentials on that worker are no longer of use to the attacker: they have what they came for, open access to the signing servers. The credentials in question aren't able to do much but claim tasks for this particular worker.

This is accurate.  The worker credentials are of limited use.  If Mallory is on a signing worker, he can DOS the other signing workers by claiming other signing tasks or by generating invalid signing tasks.  He cannot generate valid signing tasks without being able to sign the payload with a private key that will not be on the signing workers.

He can, however, sign any binaries he wants because the signing worker has access to the signing servers.

So the TC credentials are definitely not the main target.

> I would propose not to use puppet, but to use a provisioner.

I think the plan for now is to use puppet and long-lived workers; the pool size will remain static.  This works for the moment because signing is a relatively quick process and there will be a limited number of tasks to run.  We may see some spikes where the pool is overwhelmed, and some lulls where the pool is idle.

I think it's an interesting idea to have a signing worker provisioner, which can alleviate those load spikes by growing and shrinking the pool.  If the workers are granted temporary credentials and temporary access to the signing servers, this approach could work.  If OSX signing workers end up needing to be OSX as well, we'll have limited capability to grow and shrink the pool, but linux and likely windows could win here.  The provisioner definitely becomes the big target if we proceed along these lines.

It sounds like you're pushing for the latter approach now.  We should definitely discuss this.

> Since the python client library already supports using temporary credentials, I think it would make sense for scriptworker to support them too (without too much work), and then the details about how the credentials get rolled out to the workers can be worked out later. If it is decided they should use permanent credentials, having support for temporary credentials would not block that.

I have temporary credentials support code complete now.  I need to actually test it and add integration tests for it.  I'll try getting that done today.

**Comment by escapewindow** [comment]
Temp creds integration tests! https://github.com/escapewindow/scriptworker/commit/3596be396c4471aa7c645157e194af64fa1d76ba

**Comment by escapewindow** [comment]
Also added reportException support and client task functions for the script that runs under scriptworker.

I'm calling this 0.1.0, but this is very much still software under development.  Please let me know if there's anything I need/may want to get into a 0.1.1 or 0.2.0.  Thanks all!
